edition = "2018"

hard_tabs = true
max_width = 79
reorder_imports = true
use_small_heuristics = "Max"

force_multiline_blocks = false
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
overflow_delimited_expr = true
reorder_impl_items = true
unstable_features = true
wrap_comments = true
